approvedGitRepositories:
  - '**'

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

packageExtensions:
  '@redux-devtools/extension@*':
    peerDependenciesMeta:
      redux:
        optional: true

yarnPath: .yarn/releases/yarn-4.16.0.cjs
