name: Code Health Checks

on:
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: 24.17.0

jobs:
  setup:
    name: Set up Node.js and Dependencies Cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0

      - uses: actions/setup-node@v6.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v5.0.5
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('yarn.lock') }}

      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install

  checks:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        check:
          - name: Typecheck
            command: typecheck
          - name: ESLint
            command: eslint:check
          - name: Prettier
            command: prettier:check
          - name: Unit Tests
            command: test
      fail-fast: false
    name: ${{ matrix.check.name }}

    steps:
      - uses: actions/checkout@v7.0.0

      - uses: actions/setup-node@v6.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Restore node_modules
        uses: actions/cache@v5.0.5
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('yarn.lock') }}

      - run: yarn ${{ matrix.check.command }}
