name: Deploy Migrations to Production

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: echo "SUPABASE_PROJECT_ID is $SUPABASE_PROJECT_ID"
        env:
          SUPABASE_PROJECT_ID: ${{ secrets.PRODUCTION_PROJECT_ID }}

      - run: supabase link --debug --project-ref $SUPABASE_PROJECT_ID
        env:
          SUPABASE_PROJECT_ID: ${{ secrets.PRODUCTION_PROJECT_ID }}
      - run: supabase db push
        env:
          SUPABASE_PROJECT_ID: ${{ secrets.PRODUCTION_PROJECT_ID }}
