name: Deploy Migrations to Production

#on:
#  push:
#    branches:
#      - main
on: # event list
  pull_request: # on a pull request to each of these branches
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.PRODUCTION_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.PRODUCTION_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: echo "SUPABASE_PROJECT_ID is $SUPABASE_PROJECT_ID"
        env:
          SUPABASE_PROJECT_ID: ${{ secrets.PRODUCTION_PROJECT_ID }}

      - run: supabase link --debug --project-ref $SUPABASE_PROJECT_ID
        env:
          SUPABASE_PROJECT_ID: ${{ secrets.PRODUCTION_PROJECT_ID }}
      - run: supabase db push
        env:
          SUPABASE_PROJECT_ID: ${{ secrets.PRODUCTION_PROJECT_ID }}
