name: SQLFluff

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Supabase Migrations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7.0.0

      - name: Set up Python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: '3.14.6'

      - name: Install SQLFluff
        run: pip install sqlfluff

      - name: Run SQL Lint
        run: sqlfluff lint 'supabase'
